name: Release
on:
  push:
    tags:
      - '*'
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publish artifact
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.TEMP_ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.TEMP_ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.TEMP_ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
        run: |
          echo "New version: ${GITHUB_REF_NAME}"
          echo "Github username: ${GITHUB_ACTOR}"
          gradle -Pversion=${GITHUB_REF_NAME} publish --parallel
